import '@/app/globals.css'

export const metadata = {
  title: "Gopher LLC",
  description: "Generated by create next app",
};

function Application({ Component, pageProps }) {
  return <Component {...pageProps} />
}

export default Application